### ISSUE TITLE
'std::runtime_error'   what():  Invald input json file when running Getting-Started json

### ISSUE THREAD

**Issue by Alex-Beng** [polyfem/polyfem#184] opened 2023-02-20 11:38 UTC
Hello, i'm running the tutorial example on [getting_started](https://polyfem.github.io/tutorials/getting_started/). 
The running result is as follows:

```bash
$ ./build/PolyFEM_bin -j ./run.json 
[2023-02-20 19:27:09.887] [polyfem] [error] invalid input json:
error: No rule matched for "/": null
No valid rules in this list:
0: {
    "doc": "Root of the configuration file.",
    "optional": [
        "preset_problem",
        "common",
        "root_path",
        "space",
        "time",
        "contact",
        "solver",
        "boundary_conditions",
        "initial_conditions",
        "output",
        "input",
        "tests"
    ],
    "pointer": "/",
    "required": [
        "geometry",
        "materials"
    ],
    "type": "object"
}


terminate called after throwing an instance of 'std::runtime_error'
  what():  Invald input json file
```

It looks like problem with JSE([json-spec-engine](https://github.com/geometryprocessing/json-spec-engine)) parsing the json file.
Because i found the std::runtime_error was throwed on [StateInit.cpp:Line 201](https://github.com/polyfem/polyfem/blob/main/src/polyfem/state/StateInit.cpp#L201)

**Platform**
- [ ] Windows
- [ ] macOS
- [x] Linux

ubuntu 20.04.5 LTS
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
cmake 3.26.0-rc3

**Comment by zfergus** [comment] 2023-02-20 19:44
This is a bug others pointed out too. I think it was introduced in `4dee92db46c584b6f6e3eefefdc3f235d281f0ab` so if you grab `5d5cfe4f9356ab0ad640b6a6a396259e495b3d7a` or earlier it should work (let me know if not). 

The problem is I cannot reproduce it on any of our machines. I have tried on 
```
Ubuntu 22.04 jammy
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
cmake version 3.25.2
```
```
macOS Ventura 13.2.1 (w/ M2)
Apple clang version 14.0.0 (clang-1400.0.29.202)
cmake version 3.25.2
```
```
Manjaro 22.0.2 Sikaris
gcc (GCC) 11.3.0
cmake version 3.25.2
```
and all of them have worked. I will try to spin up an Ubuntu 20.04.5 LTS virtual machine and debug it there. 

If you want to help could you compile in debug mode and see if you get any assertion failure or check if the output is different?

**Comment by zfergus** [comment] 2023-02-21 03:22
I setup a VM with
```
Ubuntu 20.04 focal
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
cmake version 3.25.2
```
and still couldn't reproduce the error. The only difference I see is you are using `cmake 3.26.0-rc3`. I doubt this is the culprit though. 

I am lost on this one and am unsure how to debug it on my side, so it would be helpful if you run it in debug mode and see what you get.

**Comment by Alex-Beng** [comment] 2023-02-21 03:54
> 



> I setup a VM with
> 
> ```
> Ubuntu 20.04 focal
> gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> cmake version 3.25.2
> ```
> 
> and still couldn't reproduce the error. The only difference I see is you are using `cmake 3.26.0-rc3`. I doubt this is the culprit though.
> 
> I am lost on this one and am unsure how to debug it on my side, so it would be helpful if you run it in debug mode and see what you get.

Thanks for your reply. I traced the `args_in` variable defined in [StateInit: L160](https://github.com/polyfem/polyfem/blob/main/src/polyfem/state/StateInit.cpp#L160) in debug mode. Here is what i found.

When I run **only** with json option like `PolyFem_bin -j run.json`, the result is as followed, the `args_in`'s m_type is something null ?
![image](https://user-images.githubusercontent.com/30763045/220242171-5898ded5-96c0-4ea6-8069-2c45e351f20f.png)


However, when i run it with **multi options** like `PolyFem_bin -j run.json --max_threads 16`, the `args_in` become a something object ? And, it running up successfully.
![image](https://user-images.githubusercontent.com/30763045/220243006-3c762368-5775-4382-a788-df23d2300340.png)

**Comment by zfergus** [comment] 2023-02-21 04:33
Aha! I was always running with `-o <output>` let me try without it.

**Comment by zfergus** [comment] 2023-02-21 04:53
Yep, that was it. I just pushed a fix to `main`. Let me know if it didn't fix the problem on your end.

**Closed by zfergus** 2023-02-21 04:53 UTC
Labels: bug
